name = "TJProdEst"
uuid = "abc1b9c5-3c15-4812-bf1e-3dec67f530a4"
authors = ["Markus Trunschke <markus.trunschke@googlemail.com>"]
version = "0.0.1"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
